//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunWcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IISunCalculate")]
    public interface IISunCalculate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISunCalculate/DoWork", ReplyAction="http://tempuri.org/IISunCalculate/DoWorkResponse")]
        string DoWork(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IISunCalculate/DoWork", ReplyAction="http://tempuri.org/IISunCalculate/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IISunCalculateChannel : SunWcfClient.ServiceReference1.IISunCalculate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ISunCalculateClient : System.ServiceModel.ClientBase<SunWcfClient.ServiceReference1.IISunCalculate>, SunWcfClient.ServiceReference1.IISunCalculate {
        
        public ISunCalculateClient() {
        }
        
        public ISunCalculateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ISunCalculateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISunCalculateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ISunCalculateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string value) {
            return base.Channel.DoWork(value);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string value) {
            return base.Channel.DoWorkAsync(value);
        }
    }
}
